#! /bin/sh
# /etc/init.d/kafka: start the kafka daemon.

# chkconfig: 345 80 20
# description: kafka

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/etc/kafka/bin
KAFKA_DIR=/etc/kafka

prog=kafka
DESC="kafka daemon"

RETVAL=0

start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  cd $KAFKA_DIR
  echo -n $"Starting $prog: "
  nohup kafka-server-start.sh ./config/server.properties >> /var/log/kafka.log 2>&1 &
  RETVAL=$?
  [ $RETVAL -eq 0 ] && echo "Kafka started"
  [ $RETVAL -ne 0 ] && echo "Kafka failed to start"
  return $RETVAL
}

stop() {
  echo "Stopping Kafka"
  ps -ef | grep kafka.Kafka | grep -v grep | awk '{print $2}' | xargs kill
  [ $RETVAL -eq 0 ] && echo "Kafka stopped"
  [ $RETVAL -ne 0 ] && echo "Kafka failed to stop"
  return $RETVAL
}

reload() {
  stop
  start
}

restart() {
  stop
  start
}

case "$1" in
start)
  start
  ;;

stop)
  stop
  ;;

reload)
  reload
  ;;

restart)
  restart
  ;;

*)
  echo $"Usage: $0 {start|stop|reload|restart}"
  exit 1
esac

exit $?

